[build-system]
requires = ["hatchling>=1.25.0"]
build-backend = "hatchling.build"

[project]
name = "patchsim"
version = "0.1.0b1"
description = "A modular simulation framework for patch-based metapopulation epidemiology"
readme = "README.md"
requires-python = ">=3.11"
license = { file = "LICENSE" }
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Medical Science Apps.",
]

authors = [
    { name = "Adish Assain", email = "adish@artpark.in" },
    { name = "Sneha S", email = "sneha@artpark.in" },
    { name = "Shreya Mukherjee", email = "shreyamukherjee@artpark.in" }
]

dependencies = [
    "numpy>=1.26",
    "pandas>=2.2",
    "scipy>=1.11",
    "matplotlib>=3.8",
    "pyyaml>=6.0",
    "tqdm>=4.66",
    "networkx>=3.3",
    "SALib>=1.5",
    "rich>=14.3.3",
]

[project.urls]
Homepage = "https://github.com/dsih-artpark/patchsim"
Repository = "https://github.com/dsih-artpark/patchsim"
Documentation = "https://dsih-artpark-patchsim.readthedocs.io/"

[project.optional-dependencies]
test = [
    "pytest>=8.3.5",
    "pytest-cov",
]

docs = [
    "sphinx>=6.0",
    "myst-parser>=0.18",
    "pydata-sphinx-theme>=0.14",
]

lint = [
    "ruff",
    "mypy",
    "pre-commit>=3.0.0",
]

dev = [
    "pytest>=8.3.5",
    "pytest-cov",
    "ruff",
    "mypy",
    "rich>=13.0.0",
    "pre-commit>=3.0.0",
    "twine>=5.0.0",
]

notebook = [
    "jupyter",
    "seaborn",
    "plotly",
    "ipywidgets"
]

[project.scripts]
patchsim = "patchsim.cli:main"

[tool.ruff]
line-length = 120
target-version = "py311"

[tool.ruff.lint]
select = ["E", "F", "W", "I", "B", "RUF"]
fixable = ["ALL"]

[tool.ruff.lint.isort]
known-first-party = ["patchsim"]

[tool.hatch.build.targets.wheel]
packages = ["src/patchsim"]
include = [
    { path = "src/patchsim/templates", from = "." },
]

[tool.hatch.build.targets.sdist]
include = [
    "/src/patchsim/**",
    "/src/patchsim/templates/**",
    "/README.md",
    "/LICENSE",
]
