# Vaccination parameters
VaxDelay: 0
VaxPeriod: 365
VaxDuration: 30
VaxRate:
  BAGALKOTE: 0.0001
  BALLARI: 0.0001
  BELAGAVI: 0.0001
  BENGALURU RURAL: 0.0001
  BENGALURU URBAN: 0.0001
  CHAMARAJANAGARA: 0.0001
  CHIKKABALLAPURA: 0.0001
