# Input files
PatchFile: data/patch/sample-sir-ode-patch-population.csv
NetworkFile: data/networks/sample-network-static.csv
SeedFile: data/seeds/sample-sir-ode-patchA-2.csv
Logging: False

# Model configuration
ModelName: sample-sir-ode

# Simulation parameters
TMax: 50
Tolerance: 1e-8
MaxIter: 10000
StartDate: 2020-01-01
EndDate: 2022-12-31
OutputDir: output/sample-sir-ode
compartments: ["S", "I", "R"]
Parameters:
  beta: 0.2
  gamma: 0.1
#PatchParameters: [{"patch": "PatchA", "parameters": {"beta": 0.2, "gamma": 0.1}}, {"patch": "PatchB", "parameters": {"beta": 0.25, "gamma": 0.1}}]
Transitions: [{"from": "S", "to": "I", "rate": "beta"}, {"from": "I", "to": "R", "rate": "gamma * I"}]
